#1.Base Image
FROM alpine

 
# Environments
ENV TIMEZONE            Asia/Shanghai
ENV PHP_MEMORY_LIMIT    512M
ENV MAX_UPLOAD          50M
ENV PHP_MAX_FILE_UPLOAD 200
ENV PHP_MAX_POST        100M
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV WEBSITE_DIR /var/www/website

 
WORKDIR ${WEBSITE_DIR}

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
	&& apk upgrade \
	&& apk add \
		nginx \
        git \
		curl \
		tzdata \
		php7-fpm\
	    php7 \
	    php7-dev \
	    php7-curl \
	    php7-iconv \
	    php7-json \
	    php7-mbstring\
	    php7-opcache \
	    php7-openssl \
	    php7-pdo \
	    php7-pdo_mysql \
	    php7-session \
	    php7-mcrypt \
	    php7-xsl \
	    php7-zip \
	    php7-redis\
	    php7-gd \
		php7-fileinfo \
		php7-tokenizer \
		supervisor \
 	&& cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
	&& echo "${TIMEZONE}" > /etc/timezone \
	&& apk del tzdata \
 	&& rm -rf /var/cache/apk/* \
	&& sed -i "s|;*date.timezone =.*|date.timezone = ${TIMEZONE}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${MAX_UPLOAD}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php7/php.ini \
	&& sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= 0|i" /etc/php7/php.ini \
	&& sed -i "s|;*listen =.*|listen = /var/run/php-fpm.sock|i" /etc/php7/php-fpm.d/www.conf \
	&& mkdir -p /usr/local/var/log/php7/ \
	&& mkdir -p /usr/local/var/run/ \
	&& mkdir /run/nginx \
    && mkdir /var/log/supervisord/ \
	&& touch /run/nginx/nginx.pid \
    && mkdir $(WEBSITE_DIR)

COPY ./conf/nginx.conf /etc/nginx/nginx.conf 
COPY ./conf/supervisord.conf /etc/supervisord.conf 

EXPOSE 80
VOLUME ["/var/log/nginx","/var/log/php7","/var/log/supervisord"]
ENTRYPOINT ["./entrypoint.sh"]

