#1.Base Image
FROM alpine

 
# Environments
ENV TIMEZONE            Asia/Shanghai
ENV PHP_MEMORY_LIMIT    512M
ENV MAX_UPLOAD          50M
ENV PHP_MAX_FILE_UPLOAD 200
ENV PHP_MAX_POST        100M
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV WEBSITE_DIR /var/www/website
ENV CONF_DIR ./bootstrap
ENV DB_HOST database
ENV DB_DATABASE denny_shop
ENV DB_USERNAME shop
ENV DB_PASSWORD shop

COPY .  ${WEBSITE_DIR}
WORKDIR ${WEBSITE_DIR}


# ADD soft
# Mirror mirror switch to Alpine Linux - http://dl-4.alpinelinux.org/alpine/
RUN apk update \
	&& apk upgrade \
	&& apk add \
		nginx \
        git \
		curl \
		tzdata \
		php7-fpm\
	    php7 \
	    php7-dev \
	    php7-curl \
	    php7-iconv \
	    php7-json \
	    php7-mbstring\
	    php7-opcache \
	    php7-openssl \
	    php7-pdo \
	    php7-pdo_mysql \
	    php7-session \
	    php7-mcrypt \
	    php7-xsl \
	    php7-zip \
	    php7-redis\
	    php7-gd \
		php7-fileinfo \
		php7-tokenizer \
		supervisor \
 	&& cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
	&& echo "${TIMEZONE}" > /etc/timezone \
	&& apk del tzdata \
 	&& rm -rf /var/cache/apk/* \
	&& sed -i "s|;*date.timezone =.*|date.timezone = ${TIMEZONE}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${MAX_UPLOAD}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php7/php.ini  \
	&& sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php7/php.ini \
	&& sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= 0|i" /etc/php7/php.ini \
	&& sed -i "s|;*DB_HOST=.*|DB_HOST=${DB_HOST}|i" .env \
	&& sed -i "s|;*DB_DATABASE=.*|DB_HOST=${DB_DATABASE}|i" .env \
	&& sed -i "s|;*DB_USERNAME=.*|DB_HOST=${DB_USERNAME}|i" .env \
	&& sed -i "s|;*DB_PASSWORD=.*|DB_HOST=${DB_PASSWORD}|i" .env \
	# && sed -i "s|;*listen =.*|listen = /var/run/php-fpm.sock|i" /etc/php7/php-fpm.d/www.conf \
	&& mkdir -p /usr/local/var/log/php7/ \
	&& mkdir -p /usr/local/var/run/ \
	&& mkdir /run/nginx \
	&& mkdir /var/log/nginx/ \
	&& mkdir /var/log/php7/ \
	&& touch /run/nginx/nginx.pid \
	&& mv ${CONF_DIR}/nginx.conf /etc/nginx/nginx.conf \
	&& mv ${CONF_DIR}/supervisord.conf /etc/supervisord.conf \
	&& chmod 777 -R storage/ 




# RUN cd /var/www  && git clone https://github.com/denny071/shop-admin.git ${WEBSITE_DIR} \
# 	&& php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
#   	&& php composer-setup.php \
# 	&& php -r "unlink('composer-setup.php');" \
# 	&& mv composer.phar /usr/local/bin/composer  \
# 	&& composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
# 	&& cd ${WEBSITE_DIR} && composer update && mv .env.docker .env
 
# RUN mkdir ${WEBSITE_DIR} && mkdir  ${WEBSITE_DIR}/public && cd  ${WEBSITE_DIR}/public && echo "<?php phpinfo();" > index.php

EXPOSE 80
VOLUME ["${WEBSITE_DIR}/storage/logs",  "/var/log/"]
ENTRYPOINT ["./entrypoint.sh"]

